### ISSUE TITLE
RxTextView.textChanges crashes when one of subscriptions produces an error

### ISSUE THREAD

**Issue by netimen** [JakeWharton/RxBinding#192]
Hi Jake and everyone! Thanks for excellent job!

When I `RxTextView.textChanges` with several subscriptions and one of them produces an error (which I handle properly) the app crashes.

Here is the simple code:
```java        
RxTextView.textChanges(editQuery)
        .skip(1) // we need the error to happen when the user changes the text so skipping initial value
        .concatMap(cs -> Observable.error(new Exception("aaa")))
        .subscribe(Observers.create(o -> {}, e -> Log.e(LOG_TAG, "error" + e)));

RxTextView.textChanges(editQuery)
        .subscribe(s -> Log.e(LOG_TAG, "text: " + s));
```
When I run my app and type something in my `EditText` the app crashes:
```
java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
     at java.util.ArrayList.get(ArrayList.java:308)
     at android.widget.TextView.sendOnTextChanged(TextView.java:7679)
     at android.widget.TextView.handleTextChanged(TextView.java:7739)
     at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:9472)
     at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:964)
     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:515)
     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:454)
     at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:33)
     at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:685)
     at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:445)
     at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:340)
     at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5257)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(java.lang.reflect.Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

And it happens because when I type something, my first subscription throws an Exception and then `TextView.removeTextChangedListener` is called in `TextViewTextOnSubscribe.java:39` (because of `unsubscribe` after error). But the `TextView` is still iterating over it's watchers in the `TextView.sendOnTextChanged` method!

**Comment by dlew** [comment]
Interesting; this seems to be a concurrency issue in the Android listener itself. Having solved an almost identical problem to this recently, it's only really solvable if the emitter uses something like `CopyOnWriteArrayList` (or equivalent concurrency structure) for the listener list.

It could be easily solved by sharing the `Observable` from `textChanges()` (via something like `publish()`). Not sure what RxBinding could do to fix it besides warn users of the dangers here.

**Comment by dlew** [comment]
(In case anyone is curious, here's [the exact same problem in a slightly different context](https://github.com/trello/navi/issues/15) and [the fix I settled on for now](https://github.com/trello/navi/commit/c541812a2a1312f87ef68177630fa762a94c76c0).)

**Comment by JakeWharton** [comment]
I believe you could also add .unsubscribeOn(mainThread()) which would delay
unsubscription with a post to the next frame.

**Comment by micdm** [comment]
Have spent several hours to locate that bug. The easiest example to reproduce (place it to `Activity.onCreate` for example):
```
TextView view = new TextView(this);
RxTextView.textChanges(view).skip(1).take(1).subscribe();
RxTextView.textChanges(view).skip(1).subscribe();
view.setText("hello");
```
Workaround may be (as @dlew mentioned):
```
Observable<CharSequence> text = RxTextView.textChanges(view).skip(1).share();
text.take(1).subscribe();
text.subscribe();
view.setText("hello");
```

**Comment by JakeWharton** [comment]
Has a bug been filed on b.android.com for this ever? I'm struggling to have any desire to fix this in the library.

**Comment by micdm** [comment]
https://code.google.com/p/android/issues/detail?id=190399 is about that. Seems pretty dead.

**Comment by JakeWharton** [comment]
Great! I'll take care of it.
