### ISSUE TITLE
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: android.text.SpannableStringBuilder.class

### ISSUE THREAD

**Issue by smallsilver** [JakeWharton/RxBinding#221]
when I use the RxTextView below is the error.
I just look the source 

```javascript
  @Override public void call(final Subscriber<? super CharSequence> subscriber) {

    checkUiThread();

    final TextWatcher watcher = new TextWatcher() {
      @Override public void beforeTextChanged(CharSequence s, int start, int count, int after) {
      }

      @Override public void onTextChanged(CharSequence s, int start, int before, int count) {
        if (!subscriber.isUnsubscribed()) {
          subscriber.onNext(s);
        }
      }

      @Override public void afterTextChanged(Editable s) {
      }
    };
    view.addTextChangedListener(watcher);

    subscriber.add(new MainThreadSubscription() {
      @Override protected void onUnsubscribe() {
        view.removeTextChangedListener(watcher);
      }
    });

    // Emit initial value.
    subscriber.onNext(view.getText());
  }
}
```

the line 44 catch the error , my view.getText() will return SpannableStringBuilder

 so please deal it! thanks!

the error stack below :
```
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'rx.Subscription rx.Observable.unsafeSubscribe(rx.Subscriber)' on a null object reference
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err:     at rx.internal.operators.OperatorSwitch$SwitchSubscriber.onNext(OperatorSwitch.java:105)
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err:     at rx.internal.operators.OperatorSwitch$SwitchSubscriber.onNext(OperatorSwitch.java:60)
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err:     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:202)
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err:     at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:162)
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
01-27 14:42:39.627 19425-19425/com.lchr.diaou W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at android.os.Looper.loop(Looper.java:135)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5254)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err: Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: android.text.SpannableStringBuilder.class
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:187)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err:     at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:56)
01-27 14:42:39.628 19425-19425/com.lchr.diaou W/System.err: 	... 11 more
```

**Comment by JakeWharton** [comment]
Looks like you have code like:
```java
//...
  .observeOn(..)
  .map(..)
  .switchOnNext(something)
//...
```
and `something` is returning `null` as one of its elements.
