### ISSUE TITLE
Sequence contains no elements on fast changing view

### ISSUE THREAD

**Issue by DevAnatolii** [JakeWharton/RxBinding#238]
Hi Jake and everyone! 
I use RxLifecycle.bindView(). When I change views as fast as user can select an item in reciclerView with throttleLast 0,4 sec, the OnErrorNotImplementedException with message "Sequence contains no elements" is thrown on slow devices. 

What can I do in this case except increasing time of throttleLast? 
The Logs:
```
java.util.NoSuchElementException: Sequence contains no elements
                               at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:131)
                               at rx.internal.operators.OperatorTake$1.onCompleted(OperatorTake.java:56)
                               at rx.internal.operators.OperatorMap$1.onCompleted(OperatorMap.java:43)
                               at rx.internal.operators.OperatorFilter$1.onCompleted(OperatorFilter.java:42)
                               at rx.internal.operators.OperatorPublish$PublishSubscriber.checkTerminated(OperatorPublish.java:425)
                               at rx.internal.operators.OperatorPublish$PublishSubscriber.dispatch(OperatorPublish.java:507)
                               at rx.internal.operators.OperatorPublish$PublishSubscriber.onCompleted(OperatorPublish.java:307)
                               at rx.observers.SerializedObserver.onCompleted(SerializedObserver.java:182)
                               at rx.observers.SerializedSubscriber.onCompleted(SerializedSubscriber.java:65)
                               at rx.internal.operators.OperatorTakeUntil$1.onCompleted(OperatorTakeUntil.java:57)
                               at rx.internal.operators.OperatorTakeUntil$2.onCompleted(OperatorTakeUntil.java:72)
                               at rx.internal.operators.OperatorTakeUntil$2.onNext(OperatorTakeUntil.java:82)
                               at com.jakewharton.rxbinding.view.ViewAttachesOnSubscribe$1.onViewDetachedFromWindow(ViewAttachesOnSubscribe.java:34)
                               at android.view.View.dispatchDetachedFromWindow(View.java:13555)
                               at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:2793)
                               at android.view.ViewGroup.removeAllViewsInLayout(ViewGroup.java:4236)
                               at android.view.ViewGroup.removeAllViews(ViewGroup.java:4180)
```

**Comment by JakeWharton** [comment]
It looks like you are calling `.toSingle()` and that requires either a single element or an error. You can try operators like `defaultIfEmpty` before calling `toSingle()` to insert some kind of placeholder item or just avoid using `Single` altogether since `Observable`s are allowed to be empty.

If you need more recommendation here I would recommend (ha!) asking your question on the RxJava mailing list or on StackOverflow with the 'rxjava' tag. The problem doesn't have anything to do with RxBinding but your use of operators where RxBinding just happens to be the upstream source.

**Comment by DevAnatolii** [comment]
I checked code again. You are absolutely right. Thanks for the help.
