### ISSUE TITLE
The upstream 1.x Observable signalled a null value which is not supported in 2.x

### ISSUE THREAD

**Issue by shakil807g** [JakeWharton/RxBinding#362]
Observable<Long> intervalObservable = Observable.interval(10, TimeUnit.SECONDS);
        RxJavaInterop.toV2Observable(RxView.clicks(fab))
                .switchMap(aVoid ->
                        intervalObservable
                                .observeOn(AndroidSchedulers.mainThread())
                                    .doOnNext(aLong -> {
                                        Log.d(TAG, "click: "+aLong);
                                    })).subscribe();

i have a  steam like this and it throwing exception  

java.lang.NullPointerException: The upstream 1.x Observable signalled a null value which is not supported in 2.x 
at hu.akarnokd.rxjava.interop.ObservableV1ToObservableV2$ObservableSubscriber.onNext(ObservableV1ToObservableV2.java:58)at com.jakewharton.rxbinding.view.ViewClickOnSubscribe$1.onClick(ViewClickOnSubscribe.java:23)
                                                                      at android.view.View.performClick(View.java:5198)
                                                                      at android.view.View$PerformClick.run(View.java:21147)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JakeWharton** [comment]
This isn't a problem with the library. Map to a non-null value before converting or use the 2.0.0-SNAPSHOT.
