### ISSUE TITLE
Source not available in the IDE

### ISSUE THREAD

**Issue by oldergod** [JakeWharton/RxBinding#526]
For tracking, and because I don't know how to debug that.

The IDE would just show stubs from the class files. Clicking _download source_ doesn't do much. The logs says it fails
> 13:27	Executing tasks: [DownloadSources] in project /Users/bquenaudon/workspace/cash-android
> 13:27	Gradle build failed in 5 s 866 ms

**Comment by oldergod** [comment]
Here's what the log gave me

```
2019-10-02 13:57:33,946 [thread 537]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home 
2019-10-02 13:57:33,948 [thread 537]   INFO - ild.invoker.GradleBuildInvoker - About to execute Gradle tasks: [DownloadSources] 
2019-10-02 13:57:33,951 [thread 524]   INFO - s.plugins.gradle.GradleManager - Instructing gradle to use java from /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home 
2019-10-02 13:57:33,952 [thread 524]   INFO - ild.invoker.GradleBuildInvoker - Build command line options: [-Pandroid.injected.invoked.from.ide=true, --init-script, /private/var/folders/vc/5dwj5pms6s97y5snf5t4042c0000gn/T/ijmiscinit3.gradle] 
2019-10-02 13:57:33,957 [thread 524]   INFO - xecution.GradleExecutionHelper - Passing command-line args to Gradle Tooling API: -Pandroid.injected.invoked.from.ide=true --init-script /private/var/folders/vc/5dwj5pms6s97y5snf5t4042c0000gn/T/ijmiscinit3.gradle 
2019-10-02 13:57:34,643 [Alarm Pool]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 90 ms 
2019-10-02 13:57:37,097 [thread 534]   INFO - agnostic.FrequentEventDetector - Too many events posted, #12. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=LaterInvocator.FlushQueue,notifier=null,catchExceptions=false,when=1570039057097] on sun.lwawt.macosx.LWCToolkit@19e7f749 
2019-10-02 13:57:37,175 [thread 538]   INFO - agnostic.FrequentEventDetector - Too many events posted, #8. Event: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=LaterInvocator.FlushQueue,notifier=null,catchExceptions=false,when=1570039057175] on sun.lwawt.macosx.LWCToolkit@19e7f749 
2019-10-02 13:57:40,672 [entQueue-0]   INFO - ild.invoker.GradleBuildInvoker - Gradle build failed in 6 s 718 ms 
2019-10-02 13:57:40,674 [thread 532]   WARN - .plugins.gradle.util.GradleLog - /private/var/folders/vc/5dwj5pms6s97y5snf5t4042c0000gn/T/sources7loc/path.tmp (No such file or directory) 
java.io.FileNotFoundException: /private/var/folders/vc/5dwj5pms6s97y5snf5t4042c0000gn/T/sources7loc/path.tmp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.intellij.openapi.util.io.FileUtilRt.loadFileText(FileUtilRt.java:726)
	at com.intellij.openapi.util.io.FileUtilRt.loadFile(FileUtilRt.java:715)
	at com.intellij.openapi.util.io.FileUtilRt.loadFile(FileUtilRt.java:700)
	at com.intellij.openapi.util.io.FileUtil.loadFile(FileUtil.java:1363)
	at org.jetbrains.plugins.gradle.util.GradleAttachSourcesProvider$1$1.onSuccess(GradleAttachSourcesProvider.java:158)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$7.execute(ExternalSystemUtil.java:927)
	at com.intellij.openapi.externalSystem.util.ExternalSystemUtil$9.run(ExternalSystemUtil.java:956)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:312)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by oldergod** [comment]
I heard it might be an Android Studio problem

**Comment by JakeWharton** [comment]
```
$ unzip -l ~/Downloads/rxbinding-3.0.0-sources.jar
Archive:  /Users/jakew/Downloads/rxbinding-3.0.0-sources.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  07-23-2019 13:54   META-INF/
       25  07-23-2019 13:54   META-INF/MANIFEST.MF
        0  10-17-2018 00:37   com/
        0  10-17-2018 00:37   com/jakewharton/
        0  10-17-2018 00:37   com/jakewharton/rxbinding3/
        0  12-18-2018 17:54   com/jakewharton/rxbinding3/widget/
        0  10-17-2018 14:28   com/jakewharton/rxbinding3/internal/
        0  10-17-2018 00:37   com/jakewharton/rxbinding3/view/
---------                     -------
       25                     8 files
```
"Well there's your problem"
